# Created with WinGet Releaser using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Neosku.AviUtl2-Catalog
PackageVersion: 0.3.1
PackageLocale: ja-JP
Publisher: Neosku
PublisherUrl: https://github.com/Neosku
PublisherSupportUrl: https://github.com/Neosku/aviutl2-catalog/issues
Author: Neosku
PackageName: AviUtl2 カタログ
PackageUrl: https://github.com/Neosku/aviutl2-catalog
License: MIT
LicenseUrl: https://github.com/Neosku/aviutl2-catalog/blob/HEAD/LICENSE
Copyright: Copyright (c) 2025 Neosku
ShortDescription: AviUtl2 のプラグインやスクリプトを、検索・インストール・アップデートまで一括管理できるデスクトップ向けカタログアプリです。
Description: AviUtl2 のプラグインやスクリプトを、検索・インストール・アップデートまで一括管理できるデスクトップ向けカタログアプリです。
Moniker: aviutl2-catalog
Tags:
- aviutl2
- manager
- plugin
- script
- video
ReleaseNotes: |-
  ✨ 新機能
  - DeepLink への対応による外部リンクからのアプリ起動機能の追加
  - ニコニ・コモンズIDの登録およびコピー機能の追加
  - パッケージ登録画面におけるインストーラーテスト機能の追加
  - パッケージ登録時の詳細説明における外部 Markdown リンク指定への対応
  🛠 修正・改善
  - 画像プレビューが表示されない不具合の修正
  - 一覧画面復帰時における検索クエリ復元に対応
  - 表示順に「新着順」「トレンド順」の追加
  - デザインの調整および依存関係の更新
ReleaseNotesUrl: https://github.com/Neosku/aviutl2-catalog/releases/tag/v0.3.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
