# Created with Devicie using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: babalae.BetterGI
PackageVersion: 0.59.0
PackageLocale: en-US
Publisher: 辉鸭蛋
PublisherUrl: https://www.huiyadan.com/
PublisherSupportUrl: https://github.com/babalae/better-genshin-impact/issues
Author: 辉鸭蛋
PackageName: BetterGI
PackageUrl: https://github.com/babalae/better-genshin-impact
License: GNU General Public License v3.0
LicenseUrl: https://github.com/babalae/better-genshin-impact/blob/main/LICENSE
Copyright: Copyright (c) 辉鸭蛋
ShortDescription: BetterGI · UI Automation Testing Tools For Genshin Impact
Description: 📦BetterGI · UI Automation Testing Tools For Genshin Impact
Tags:
- auto-fish
- auto-skip
- automatic
- genius-invokation-tcg
- genshin
- genshin-impact
ReleaseNotesUrl: https://github.com/babalae/better-genshin-impact/releases/tag/0.59.0
ManifestType: locale
ManifestVersion: 1.12.0
