# Created with WinGet Releaser using komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: CodeMiracle.MagicBox
PackageVersion: 1.1.1
PackageLocale: en-US
Publisher: dmqj123
PublisherUrl: https://github.com/dmqj123
PublisherSupportUrl: https://github.com/dmqj123/magic_box/issues
Author: Code miracle
PackageName: MagicBox
PackageUrl: https://github.com/dmqj123/magic_box
License: Proprietary (No license)
ShortDescription: Universal system-level search box
Description: |
  A powerful and versatile desktop search utility built with Flutter. Magic Box is a floating search tool that allows users to quickly search and retrieve information using various plugins, providing an efficient way to access files, applications, and web content from a single interface.
ReleaseNotes: |-
  解决了用户提出的bug；
  解决了提出问题的用户；
  😁上面的是骗你的，其实这次更新啥都没更新就是换了个版本号，为了解决微软的winget中的包的版本不匹配的问题
ReleaseNotesUrl: https://github.com/dmqj123/magic_box/releases/tag/1.1.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
